#!/bin/python

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(year):

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    year = int(raw_input())

    result = solve(year)

    fptr.write(result + '\n')

    fptr.close()
